### ISSUE TITLE
Please add the stack name to logging

### ISSUE THREAD

**Issue by gabrielprioli** [dynatrace-oss/dynatrace-aws-log-forwarder#44]
In the following line we do not explicitly say to which stack we are subscribing to:

https://github.com/dynatrace-oss/dynatrace-aws-log-forwarder/blob/8f1624f502476a37ff7e44c573f86f8831739b41/dynatrace-aws-logs.sh#L371

However, in the unsubscription process we do output the stack name:

https://github.com/dynatrace-oss/dynatrace-aws-log-forwarder/blob/8f1624f502476a37ff7e44c573f86f8831739b41/dynatrace-aws-logs.sh#L466

I believe it would be valuable to add the stack name in the subscription as well, even if it is the default one.

**Comment by mmajcher** [comment]
It will be added to next release 👍

**Comment by mmajcher** [comment]
Pull request https://github.com/dynatrace-oss/dynatrace-aws-log-forwarder/pull/45
