### ISSUE TITLE
Static severity level of "INFO" being set in transformation.py

### ISSUE THREAD

**Issue by bradenrichardsonfmg** [dynatrace-oss/dynatrace-aws-log-forwarder#67]
def transform_single_log_entry(log_event, batch_metadata, record_metadata) -> Dict:
    parsed_record = {
        'content': log_event["message"],
        'cloud.provider': 'aws',
        'cloud.account.id': batch_metadata.account_id,
        'cloud.region': batch_metadata.region,
        'aws.log_group': record_metadata.log_group,
        'aws.log_stream': record_metadata.log_stream,
        'aws.region': batch_metadata.region,
        'aws.account.id': batch_metadata.account_id,
        'severity': 'INFO',
    }

Note that severity is being set as 'INFO' statically, I assume this would only be happening when using the default configuration for single log entries

**Comment by mmajcher** [comment]
Yes, it is set as default here, few lines below there is metadata engine being applied which will overwrite some of those values.
Unfortunately we have severity detection (& overwrite) in very few cases. This is an improvement which is scheduled for future.

**Comment by bkaya-spryker** [comment]
Hi @mmajcher,
Should we expect that improvement in near future? Some of the customers also complaining about it.
