### ISSUE TITLE
Question: Why are logs not also delivered to S3?

### ISSUE THREAD

**Issue by paulalex** [dynatrace-oss/dynatrace-aws-log-forwarder#70]
I am using a cloud formation stack supplied by dynatrace to create the stream and I using this lambda function. The logs do get sent to the active gate and this is working fine, and with some debugging I can see the lambda handler returns records when it ends.

There is never anything in the S3 bucket attached to the stream though and I cannot figure out why, or if this is the expected behaviour.

Can anyone help me?

**Comment by wojtasskorcz** [comment]
Hi @paulalex ! The logs should be delivered to the S3 bucket created with the CloudFormation stack and deleted only after seven days. This is configured here: https://github.com/dynatrace-oss/dynatrace-aws-log-forwarder/blob/master/dynatrace-aws-log-forwarder-template.yaml#L129

I just checked in our dev environment and can see this working correctly. Not sure what may be the problem on your side. Have you checked CloudTrail if there are any traces of failed operations involving this bucket?

**Comment by paulalex** [comment]
Hi @wojtasskorcz thanks, I think I have gotten to the bottom of the issue now and I can close this, it was a user error. I have rewritten the template into terraform as we do not use cloud formation generally.

This was caused because the role on the stream didnt have access to a customer manager CMK but it was invisible until I enabled destination error logging and gave cloudwatch logs permission.

Thank you for confirming that logs should be stored and for taking time to look at this.
