### ISSUE TITLE
Allow tags to be passed through to cloudformation stack

### ISSUE THREAD

**Issue by mattcat10** [dynatrace-oss/dynatrace-aws-log-forwarder#78]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
We would like the ability to add tags to the cloudformation stack when it is created via the deployment script. Other parameters for stack creation should also be allowed to be passed through

**Describe alternatives you've considered**
Calling update stack manually requires required parameters (DynatraceEnvironmentUrl, UseExistingActiveGate, DynatracePaasToken, MaxLogContentLength, DynatraceApiKey), so it would be nice to just be able to tag the stack at creation  

**Additional context**

**Comment by NematulloKozimov** [comment]
Thanks for sharing a good idea. You can expect this to happen soon.

**Comment by nikita-paskal-dynatrace** [comment]
Hello, changes have been placed. Right now you can use **--tags**
https://github.com/dynatrace-oss/dynatrace-aws-log-forwarder/pull/81
