### ISSUE TITLE
Error with docs

### ISSUE THREAD

**Issue by guisesterheim** [dynatrace-oss/dynatrace-aws-log-forwarder#85]
Hello!

I've been following this link (https://www.dynatrace.com/support/help/setup-and-configuration/setup-on-cloud-platforms/amazon-web-services/amazon-web-services-integrations/aws-log-forwarder#prereq) and I'm getting several errors while trying to use this forwarder.

I'm running on Mac, so that's a bit different. I've been updating the commands to make it work.
But then there's the <<HTTP_CODE>> placeholder which is confusing on how it's used.

Can you guys please help with how to run this on Mac?

Thanks!

**Comment by joaquinfilipic-dynatrace** [comment]
Hello, 
I am not sure what placeholder you're referring to, but please ask in our slack channel (maybe someone already knows about Mac required adjustments) or directly create and RFA.
