### ISSUE TITLE
Allow AWS account overide

### ISSUE THREAD

**Issue by edfenergy-stevebowerman** [dynatrace-oss/dynatrace-aws-log-forwarder#86]
**Is your feature request related to a problem? Please describe.**
We are looking to build a single ingest route for AWS cloudwatch logs as it helps manage our deployment easier and make life easier for our target teams to get their log data in.

However, this approach means that whilst we are ingesting log files for multiple AWS accounts, the Lambda sets the `aws.account.id` value to our ingestion AWS account.

**Describe the solution you'd like**
We'd like to decorate our logs so that the `aws.account.id` value is set to the originating AWS account.

**Comment by NematulloKozimov** [comment]
Hi, you can expect this to be available in near future
